baseurl = "https://mateus4k.github.io"
languageCode = "en-us"
paginate = 8
theme = "terminal"

[params]
centerTheme = true
contentTypeName = "posts"
fullWidthTheme = false
readingTime = true
showLanguageSelector = false
showLastUpdated = false
showMenuItems = 2
Toc = true
staticDir = ["static"]
themeColor = "orange"

[languages]
[languages.en]
copyright = ""
keywords = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "Backend engineering"
title = "Mateus4k"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "mateus4k"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v3'
