baseurl = "https://mateus4k.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "Mateus4k"
enableEmoji = true

[pagination]
pagerSize = 10

[markup.highlight]
style = "github-dark"

[params]
author = "Mateus"
info = "Backend engineering"
description = "Mateus's personal blog"
keywords = "blog,backend,developer"
colorScheme = "dark"
since = 2023
hideColorSchemeToggle = true
maxSeeAlsoItems = 4
staticDir = ["static"]

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/mateus4k"

# https://comments.app/
[params.telegram]
siteID = "9b-TC4ZR"
limit = "4"
color = "42A5F5"
outlined = "1"
dark = "1"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[module]
[[module.imports]]
path = 'github.com/luizdepra/hugo-coder'
